<?php

declare(strict_types=1);

namespace Entrepeneur4lyf\LaravelConductor\Commands;

use Illuminate\Console\Command;
use Illuminate\Contracts\Config\Repository as ConfigRepository;
use Illuminate\Filesystem\Filesystem;

final class MakeWorkflowCommand extends Command
{
    protected $signature = 'conductor:make-workflow {name : Workflow name} {--force : Overwrite existing files}';

    protected $description = 'Scaffold a workflow definition, prompt template, and JSON schema.';

    public function handle(Filesystem $files, ConfigRepository $config): int
    {
        $workflowName = trim((string) $this->argument('name'));
        $workflowRoot = $this->workflowRoot($config);
        $workflowPath = $workflowRoot.DIRECTORY_SEPARATOR.$workflowName.'.yaml';
        $promptPath = $workflowRoot.DIRECTORY_SEPARATOR.'prompts'.DIRECTORY_SEPARATOR.'research.md.j2';
        $schemaPath = $workflowRoot.DIRECTORY_SEPARATOR.'schemas'.DIRECTORY_SEPARATOR.'research-output.json';

        if (! $this->option('force') && (
            $files->exists($workflowPath)
            || $files->exists($promptPath)
            || $files->exists($schemaPath)
        )) {
            $this->error('Workflow scaffold already exists. Use --force to overwrite existing files.');

            return self::FAILURE;
        }

        $files->ensureDirectoryExists(dirname($workflowPath));
        $files->ensureDirectoryExists(dirname($promptPath));
        $files->ensureDirectoryExists(dirname($schemaPath));

        $files->put($workflowPath, $this->renderStub('workflow.stub.yaml', [
            '{{ workflow_name }}' => $workflowName,
            '{{ workflow_description }}' => 'Workflow generated by conductor:make-workflow.',
            '{{ agent_name }}' => 'research-agent',
            '{{ prompt_template }}' => 'prompts/research.md.j2',
            '{{ output_schema }}' => '@schemas/research-output.json',
            '{{ wait_for }}' => 'approval',
        ]));

        $files->put($promptPath, $this->renderStub('prompt.stub.md.j2', [
            '{{ workflow_name }}' => $workflowName,
            '{{ step_name }}' => 'research',
            '{{ output_schema }}' => '@schemas/research-output.json',
            '{{ wait_for }}' => 'approval',
        ]));

        $files->put($schemaPath, $this->renderStub('schema.stub.json', [
            '{{ workflow_name }}' => $workflowName,
        ]));

        $this->info(sprintf('Created workflow scaffold for [%s].', $workflowName));
        $this->line($workflowPath);
        $this->line($promptPath);
        $this->line($schemaPath);

        return self::SUCCESS;
    }

    private function workflowRoot(ConfigRepository $config): string
    {
        $paths = (array) $config->get('conductor.definitions.paths', []);
        $root = (string) ($paths[0] ?? base_path('workflows'));

        return rtrim($root, DIRECTORY_SEPARATOR);
    }

    /**
     * @param  array<string, string>  $replacements
     */
    private function renderStub(string $stub, array $replacements = []): string
    {
        $path = $this->packageRoot().DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR.$stub;
        $contents = file_get_contents($path);

        if ($contents === false) {
            throw new \RuntimeException(sprintf('Stub [%s] could not be read.', $stub));
        }

        return str_replace(array_keys($replacements), array_values($replacements), $contents);
    }

    private function packageRoot(): string
    {
        return dirname(__DIR__, 2);
    }
}
